# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: developer.proto for package 'developer'

require 'grpc'
require 'developer_pb'

module Developer
  module DeveloperService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'developer.DeveloperService'

      # developer init session
      rpc :initSession, SessionRequest, Session
      # get balance
      rpc :getBalance, Session, AppBankBalance
      # send coin from bank
      rpc :sendTxFromBank, BankTx, BankTx
    end

    Stub = Service.rpc_stub_class
  end
end
