# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: global.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "VersionInfo" do
    optional :version, :string, 1
    optional :service, :string, 2
    optional :description, :string, 3
    optional :access_right, :string, 4
  end
end

VersionInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("VersionInfo").msgclass
