# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: tsv.proto for package 'tsv'

require 'grpc'
require 'tsv_pb'

module Tsv
  module TSVService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'tsv.TSVService'

      # service version
      rpc :versionInfo, Google::Protobuf::Empty, VersionInfo
      #
      # get provider from provider name
      # 
      rpc :getProvider, QRRequest, Provider
      #
      # when provider's key store is akey open platform, provider can generate and bind key , user and device.
      #
      rpc :generateKey, KeyRequest, KeyResponse
      #
      # bind key
      rpc :bindKey, BindKeyRequest, TwoStepVerifyStauts
      #
      # verify code, when code resource is akey open platform
      rpc :verifyCode, VerifyCodeRequest, TwoStepVerifyStauts
    end

    Stub = Service.rpc_stub_class
  end
end
