<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: developer.proto

namespace Developer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>developer.BankAddress</code>
 */
class BankAddress extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * Generated from protobuf field <code>string address = 2;</code>
     */
    private $address = '';
    /**
     * Generated from protobuf field <code>string owner = 3;</code>
     */
    private $owner = '';
    /**
     * Generated from protobuf field <code>string private_key = 4;</code>
     */
    private $private_key = '';
    /**
     * Generated from protobuf field <code>string main_net = 5;</code>
     */
    private $main_net = '';
    /**
     * Generated from protobuf field <code>string crypto_type = 6;</code>
     */
    private $crypto_type = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $address
     *     @type string $owner
     *     @type string $private_key
     *     @type string $main_net
     *     @type string $crypto_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Developer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string address = 2;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string owner = 3;</code>
     * @return string
     */
    public function getOwner()
    {
        return $this->owner;
    }

    /**
     * Generated from protobuf field <code>string owner = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOwner($var)
    {
        GPBUtil::checkString($var, True);
        $this->owner = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string private_key = 4;</code>
     * @return string
     */
    public function getPrivateKey()
    {
        return $this->private_key;
    }

    /**
     * Generated from protobuf field <code>string private_key = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPrivateKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->private_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string main_net = 5;</code>
     * @return string
     */
    public function getMainNet()
    {
        return $this->main_net;
    }

    /**
     * Generated from protobuf field <code>string main_net = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMainNet($var)
    {
        GPBUtil::checkString($var, True);
        $this->main_net = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string crypto_type = 6;</code>
     * @return string
     */
    public function getCryptoType()
    {
        return $this->crypto_type;
    }

    /**
     * Generated from protobuf field <code>string crypto_type = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCryptoType($var)
    {
        GPBUtil::checkString($var, True);
        $this->crypto_type = $var;

        return $this;
    }

}

