<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: developer.proto

namespace Developer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>developer.SessionRequest</code>
 */
class SessionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string access_key = 1;</code>
     */
    private $access_key = '';
    /**
     * Generated from protobuf field <code>string crypto_type = 2;</code>
     */
    private $crypto_type = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $access_key
     *     @type string $crypto_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Developer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string access_key = 1;</code>
     * @return string
     */
    public function getAccessKey()
    {
        return $this->access_key;
    }

    /**
     * Generated from protobuf field <code>string access_key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAccessKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->access_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string crypto_type = 2;</code>
     * @return string
     */
    public function getCryptoType()
    {
        return $this->crypto_type;
    }

    /**
     * Generated from protobuf field <code>string crypto_type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCryptoType($var)
    {
        GPBUtil::checkString($var, True);
        $this->crypto_type = $var;

        return $this;
    }

}

