<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: developer.proto

namespace Developer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>developer.UnAllocateGas</code>
 */
class UnAllocateGas extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * Generated from protobuf field <code>string main_net = 2;</code>
     */
    private $main_net = '';
    /**
     * Generated from protobuf field <code>string gas_type = 3;</code>
     */
    private $gas_type = '';
    /**
     * Generated from protobuf field <code>uint32 decimal = 4;</code>
     */
    private $decimal = 0;
    /**
     * Generated from protobuf field <code>string session_id = 5;</code>
     */
    private $session_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $main_net
     *     @type string $gas_type
     *     @type int $decimal
     *     @type string $session_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Developer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string main_net = 2;</code>
     * @return string
     */
    public function getMainNet()
    {
        return $this->main_net;
    }

    /**
     * Generated from protobuf field <code>string main_net = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMainNet($var)
    {
        GPBUtil::checkString($var, True);
        $this->main_net = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string gas_type = 3;</code>
     * @return string
     */
    public function getGasType()
    {
        return $this->gas_type;
    }

    /**
     * Generated from protobuf field <code>string gas_type = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setGasType($var)
    {
        GPBUtil::checkString($var, True);
        $this->gas_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 decimal = 4;</code>
     * @return int
     */
    public function getDecimal()
    {
        return $this->decimal;
    }

    /**
     * Generated from protobuf field <code>uint32 decimal = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setDecimal($var)
    {
        GPBUtil::checkUint32($var);
        $this->decimal = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string session_id = 5;</code>
     * @return string
     */
    public function getSessionId()
    {
        return $this->session_id;
    }

    /**
     * Generated from protobuf field <code>string session_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->session_id = $var;

        return $this;
    }

}

