<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tsv.proto

namespace Tsv;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>tsv.BindKeyRequest</code>
 */
class BindKeyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string key = 1;</code>
     */
    private $key = '';
    /**
     * Generated from protobuf field <code>string provider_name = 2;</code>
     */
    private $provider_name = '';
    /**
     * Generated from protobuf field <code>string verify_code = 3;</code>
     */
    private $verify_code = '';
    /**
     * Generated from protobuf field <code>string label = 4;</code>
     */
    private $label = '';
    /**
     * Generated from protobuf field <code>string platform = 5;</code>
     */
    private $platform = '';
    /**
     * Generated from protobuf field <code>string device_id = 6;</code>
     */
    private $device_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key
     *     @type string $provider_name
     *     @type string $verify_code
     *     @type string $label
     *     @type string $platform
     *     @type string $device_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Tsv::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string key = 1;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>string key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string provider_name = 2;</code>
     * @return string
     */
    public function getProviderName()
    {
        return $this->provider_name;
    }

    /**
     * Generated from protobuf field <code>string provider_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setProviderName($var)
    {
        GPBUtil::checkString($var, True);
        $this->provider_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string verify_code = 3;</code>
     * @return string
     */
    public function getVerifyCode()
    {
        return $this->verify_code;
    }

    /**
     * Generated from protobuf field <code>string verify_code = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setVerifyCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->verify_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string label = 4;</code>
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * Generated from protobuf field <code>string label = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setLabel($var)
    {
        GPBUtil::checkString($var, True);
        $this->label = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string platform = 5;</code>
     * @return string
     */
    public function getPlatform()
    {
        return $this->platform;
    }

    /**
     * Generated from protobuf field <code>string platform = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPlatform($var)
    {
        GPBUtil::checkString($var, True);
        $this->platform = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string device_id = 6;</code>
     * @return string
     */
    public function getDeviceId()
    {
        return $this->device_id;
    }

    /**
     * Generated from protobuf field <code>string device_id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_id = $var;

        return $this;
    }

}

