<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tsv.proto

namespace Tsv;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>tsv.Provider</code>
 */
class Provider extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>string qr_pattern = 3;</code>
     */
    private $qr_pattern = '';
    /**
     * Generated from protobuf field <code>string logo_url = 4;</code>
     */
    private $logo_url = '';
    /**
     * Generated from protobuf field <code>string verify_api = 5;</code>
     */
    private $verify_api = '';
    /**
     * Generated from protobuf field <code>bool is_akey = 6;</code>
     */
    private $is_akey = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $name
     *     @type string $qr_pattern
     *     @type string $logo_url
     *     @type string $verify_api
     *     @type bool $is_akey
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Tsv::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string qr_pattern = 3;</code>
     * @return string
     */
    public function getQrPattern()
    {
        return $this->qr_pattern;
    }

    /**
     * Generated from protobuf field <code>string qr_pattern = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setQrPattern($var)
    {
        GPBUtil::checkString($var, True);
        $this->qr_pattern = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string logo_url = 4;</code>
     * @return string
     */
    public function getLogoUrl()
    {
        return $this->logo_url;
    }

    /**
     * Generated from protobuf field <code>string logo_url = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setLogoUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->logo_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string verify_api = 5;</code>
     * @return string
     */
    public function getVerifyApi()
    {
        return $this->verify_api;
    }

    /**
     * Generated from protobuf field <code>string verify_api = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setVerifyApi($var)
    {
        GPBUtil::checkString($var, True);
        $this->verify_api = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_akey = 6;</code>
     * @return bool
     */
    public function getIsAkey()
    {
        return $this->is_akey;
    }

    /**
     * Generated from protobuf field <code>bool is_akey = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsAkey($var)
    {
        GPBUtil::checkBool($var);
        $this->is_akey = $var;

        return $this;
    }

}

