<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tsv.proto

namespace Tsv;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>tsv.QRRequest</code>
 */
class QRRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string provider_name = 1;</code>
     */
    private $provider_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $provider_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Tsv::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string provider_name = 1;</code>
     * @return string
     */
    public function getProviderName()
    {
        return $this->provider_name;
    }

    /**
     * Generated from protobuf field <code>string provider_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setProviderName($var)
    {
        GPBUtil::checkString($var, True);
        $this->provider_name = $var;

        return $this;
    }

}

