<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace App\User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>app.user.AppUser</code>
 */
class AppUser extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * Generated from protobuf field <code>string app_id = 2;</code>
     */
    private $app_id = '';
    /**
     * Generated from protobuf field <code>string session_id = 3;</code>
     */
    private $session_id = '';
    /**
     * Generated from protobuf field <code>string secret_private_key = 4;</code>
     */
    private $secret_private_key = '';
    /**
     * Generated from protobuf field <code>string secret_public_key = 5;</code>
     */
    private $secret_public_key = '';
    /**
     * Generated from protobuf field <code>string nonce = 6;</code>
     */
    private $nonce = '';
    /**
     * Generated from protobuf field <code>string app_user_id = 7;</code>
     */
    private $app_user_id = '';
    /**
     * Generated from protobuf field <code>string crypto_type = 8;</code>
     */
    private $crypto_type = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $app_id
     *     @type string $session_id
     *     @type string $secret_private_key
     *     @type string $secret_public_key
     *     @type string $nonce
     *     @type string $app_user_id
     *     @type string $crypto_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string app_id = 2;</code>
     * @return string
     */
    public function getAppId()
    {
        return $this->app_id;
    }

    /**
     * Generated from protobuf field <code>string app_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAppId($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string session_id = 3;</code>
     * @return string
     */
    public function getSessionId()
    {
        return $this->session_id;
    }

    /**
     * Generated from protobuf field <code>string session_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->session_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string secret_private_key = 4;</code>
     * @return string
     */
    public function getSecretPrivateKey()
    {
        return $this->secret_private_key;
    }

    /**
     * Generated from protobuf field <code>string secret_private_key = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSecretPrivateKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->secret_private_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string secret_public_key = 5;</code>
     * @return string
     */
    public function getSecretPublicKey()
    {
        return $this->secret_public_key;
    }

    /**
     * Generated from protobuf field <code>string secret_public_key = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSecretPublicKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->secret_public_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string nonce = 6;</code>
     * @return string
     */
    public function getNonce()
    {
        return $this->nonce;
    }

    /**
     * Generated from protobuf field <code>string nonce = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setNonce($var)
    {
        GPBUtil::checkString($var, True);
        $this->nonce = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string app_user_id = 7;</code>
     * @return string
     */
    public function getAppUserId()
    {
        return $this->app_user_id;
    }

    /**
     * Generated from protobuf field <code>string app_user_id = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setAppUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string crypto_type = 8;</code>
     * @return string
     */
    public function getCryptoType()
    {
        return $this->crypto_type;
    }

    /**
     * Generated from protobuf field <code>string crypto_type = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setCryptoType($var)
    {
        GPBUtil::checkString($var, True);
        $this->crypto_type = $var;

        return $this;
    }

}

